# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job_1:
    name: Fluter Build Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - name: Build Flutter
      run: cd src/hotel_app && flutter build web
  
  job_2:
    name: Python Back-end Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install Library
      run: pip install fastapi hypercorn
      
    - name: Copy Test Files
      run: cp -f .github/testscripts/data_import.py src/hotel_svr/data_import.py
      
    - name: Initialize Database
      run: cd src/hotel_svr && python3 data.py
      
    - name: Test Server
      run: cd src/hotel_svr && (timeout 30s hypercorn server:app ||  [[ $? -eq 124 ]])
  
